//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public long menu_id { get; set; }
        public string slug { get; set; }
        public string icon { get; set; }
        public string naslov_menu { get; set; }
        public Nullable<long> parent_id { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public Nullable<int> redosled { get; set; }
        public Nullable<long> vrsta_korisnici_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string tekst { get; set; }
        public string layout { get; set; }
    
        public virtual vrsta_korisnici vrsta_korisnici { get; set; }
    }
}
