//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parking_karte
    {
        public long parking_karte_id { get; set; }
        public Nullable<long> parking_zona_id { get; set; }
        public string registarske_tablice { get; set; }
        public Nullable<System.DateTime> parking_karata_datum_isteka { get; set; }
        public Nullable<long> nacin_placanja_id { get; set; }
        public Nullable<System.DateTime> parking_karta_datum_kupovine { get; set; }
        public string parking_kazna { get; set; }
        public Nullable<long> korisnici_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual korisnici korisnici { get; set; }
        public virtual nacin_placanja nacin_placanja { get; set; }
        public virtual parking_zone parking_zone { get; set; }
    }
}
