//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingAuth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingServisPajaASPEntities : DbContext
    {
        public ParkingServisPajaASPEntities()
            : base("name=ParkingServisPajaASPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<korisnici> korisnici { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<nacin_placanja> nacin_placanja { get; set; }
        public virtual DbSet<parking_karte> parking_karte { get; set; }
        public virtual DbSet<parking_zone> parking_zone { get; set; }
        public virtual DbSet<vrsta_korisnici> vrsta_korisnici { get; set; }
    }
}
